### ISSUE TITLE
Uncaught TypeError: Cannot read property '2' of undefined

### ISSUE THREAD

**Issue by KoltPenny** [grischa/atom-emacs-tab#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [emacs-tab](https://github.com/grischa/atom-emacs-tab) package 0.1.0

### Stack Trace

Uncaught TypeError: Cannot read property '2' of undefined

```
At C:\Users\kille\.atom\packages\emacs-tab\lib\emacs-flow.coffee:17

TypeError: Cannot read property '2' of undefined
    at EmacsFlow.module.exports.EmacsFlow.autoIndent (/packages/emacs-tab/lib/emacs-flow.coffee:17:40)
    at /packages/emacs-tab/lib/index.coffee:14:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.19.0/resources/app/src/command-registry.js:265:35)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.19.0/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.19.0/resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -2:40.8.0 emacs-flow:auto-indent (input.hidden-input)
     -0:23.9.0 settings-view:open (input.hidden-input)
     -0:08.1.0 emacs-flow:auto-indent (input.hidden-input)
```

### Non-Core Packages

```
atomic-emacs 0.12.0 
emacs-tab 0.1.0 
```

**Comment by messju** [comment]
I had the same Problem. This fixed it for me: (in ~/.atom/.apm/emacs-tab)
```
diff --git a/lib/emacs-flow.coffee b/lib/emacs-flow.coffee
index d315a75..f8315df 100644
--- a/lib/emacs-flow.coffee
+++ b/lib/emacs-flow.coffee
@@ -14,7 +14,7 @@ class EmacsFlow
     [row, _] = editor.getCursorBufferPosition().toArray()
     line = editor.selections[0].cursor.getBufferRow()
     if editor.selections[0].isEmpty()
-      if /\s/.test(editor.buffer.lines[row])
+      if /\s/.test(editor.buffer.getLines()[row])
         editor.autoIndentSelectedRows(row)
       else
         # editor.indent()

```

I don't know if there was an API change in atoms TextBuffer from 1.18 to 1.19 or so. I could not find any references, but I'm not that knowledgable in atom development or atom package development.

**Comment by grischa** [comment]
I think there was an API change. I fixed it with `.getLineForRow(row)`.

https://atom.io/docs/api/v1.6.0/TextBuffer#instance-lineForRow
